version: '3.8'

services:
  mongo:
    image: mongo:4.4.23
    container_name: scrapy_spiders_mongo
    environment:
      - 'TZ=Asia/Shanghai'
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD}
      - MONGO_INITDB_DATABASE=${MONGO_DB}
    restart: always
    ports:
      - '27017:27017'
    volumes:
      - ./data:/data/db
