version: '3.8'

services:
  mongo:
    image: mongo:6.0.8
    container_name: scrapy_spiders_mongo
    environment:
      - "TZ=Asia/Shanghai"
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
      - MONGO_INITDB_DATABASE=products_crawler
    restart: always
    ports:
      - '27017:27017'
    volumes:
      - ./data:/data/db
